# Generated by Django 5.2.8 on 2025-12-03 20:09

import pgvector.django.vector
from pgvector.django import VectorExtension

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        VectorExtension(),  # Ensures the vector extension is enabled in Postgres
        migrations.CreateModel(
            name='MotnGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotnShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motn_id', models.CharField(help_text='Show identifier as used by Streaming Availability API (often IMDb or TMDb id).', max_length=64, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('original_title', models.CharField(blank=True, max_length=512)),
                ('overview', models.TextField(blank=True)),
                ('show_type', models.CharField(blank=True, help_text="Type of show, e.g. 'movie' or 'series'.", max_length=16)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, help_text='Runtime in minutes.', null=True)),
                ('age_certification', models.CharField(blank=True, help_text="Age rating / certification (e.g. 'PG-13', 'TV-MA').", max_length=16)),
                ('imdb_id', models.CharField(blank=True, max_length=32)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('imdb_vote_count', models.IntegerField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('tmdb_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('original_language', models.CharField(blank=True, max_length=8)),
                ('cast', models.JSONField(blank=True, default=list, help_text='List of cast members.')),
                ('directors', models.JSONField(blank=True, default=list, help_text='List of directors.')),
                ('countries', models.JSONField(blank=True, default=list, help_text='Production / availability countries.')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Additional tags/keywords from the API, if any.')),
                ('poster_urls', models.JSONField(blank=True, default=dict, help_text="Dict of poster URLs keyed by size (e.g. '92', '185', 'original').")),
                ('backdrop_urls', models.JSONField(blank=True, default=dict, help_text='Dict of backdrop URLs keyed by size.')),
                ('streaming_options', models.JSONField(blank=True, default=dict, help_text='Map of country code -> list of streaming options.')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movie of the Night show',
                'verbose_name_plural': 'Movie of the Night shows',
            },
        ),
        migrations.CreateModel(
            name='MotnShowGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='imdbmovie',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.RemoveField(
            model_name='imdbmovie',
            name='genres',
        ),
        migrations.AlterField(
            model_name='imdbmovie',
            name='original_title',
            field=models.CharField(blank=True, max_length=460),
        ),
        migrations.AlterField(
            model_name='imdbmovie',
            name='title',
            field=models.CharField(max_length=460),
        ),
        migrations.CreateModel(
            name='ImdbMovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.imdbgenre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.imdbmovie')),
            ],
        ),
        migrations.AddIndex(
            model_name='imdbmovie',
            index=models.Index(fields=['imdb_id'], name='movies_imdb_imdb_id_8a56c3_idx'),
        ),
        migrations.AddField(
            model_name='motnshowgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.motngenre'),
        ),
        migrations.AddField(
            model_name='motnshowgenre',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.motnshow'),
        ),
        migrations.AddField(
            model_name='motnshow',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='List of genres as returned by the API.', related_name='shows', through='movies.MotnShowGenre', to='movies.motngenre'),
        ),
        migrations.AddField(
            model_name='imdbmovie',
            name='genres',
            field=models.ManyToManyField(through='movies.ImdbMovieGenre', to='movies.imdbgenre'),
        ),
        migrations.AlterUniqueTogether(
            name='imdbmoviegenre',
            unique_together={('movie', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='motnshowgenre',
            unique_together={('show', 'genre')},
        ),
        migrations.AddIndex(
            model_name='motnshow',
            index=models.Index(fields=['motn_id'], name='movies_motn_motn_id_0b0837_idx'),
        ),
        migrations.AddIndex(
            model_name='motnshow',
            index=models.Index(fields=['imdb_id'], name='movies_motn_imdb_id_8ace9b_idx'),
        ),
        migrations.AddIndex(
            model_name='motnshow',
            index=models.Index(fields=['tmdb_id'], name='movies_motn_tmdb_id_bc1ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='motnshow',
            index=models.Index(fields=['show_type', 'year'], name='movies_motn_show_ty_1bae6a_idx'),
        ),
    ]
